include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AntiDarkSwordUI
AntiDarkSwordUI_FILES = Tweak.x
AntiDarkSwordUI_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
AntiDarkSwordUI_FRAMEWORKS = Foundation UIKit WebKit JavaScriptCore

include $(THEOS_MAKE_PATH)/tweak.mk
