include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AntiDarkSwordDaemon
AntiDarkSwordDaemon_FILES = Tweak.x
AntiDarkSwordDaemon_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
AntiDarkSwordDaemon_FRAMEWORKS = Foundation CoreFoundation

include $(THEOS_MAKE_PATH)/tweak.mk
